name: pepintrie_plugin
version: 1.1
author: Enta12
main: fr.pepintrie.pepintrieplugin.Main
api-version: 1.17
commands:
  licence:
    description: Change paper into shop licence
    permission: licence.use
  gods:
    create:
      description: commands to crete a new god
      permission: gods.admin
    delete:
      description: commands to delete a god
      permission: gods.admin
    rename:
      description: commands to rename a god
      permission: gods.admin
    list:
      description : commands to list gods in the game
      permission: gods.list
  altars:
    list:
      description: list altar of a god
      permission: altar.list
    set:
      size:
        description: set size of an altar
        permission: altar.size
    get:
      size:
        description: get size of an altar
        permission: altar.size
  quests:
    list:
      description: list quest of an altar
      persission: quests.admin
    create:
      description: create a quest for a god
      persission: quests.admin