name: deploy-serv-dev

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install-java
        run: sudo apt update && sudo apt -y install default-jdk
      - name: build plugin
        run: jar cf plugin.jar .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: deploy
        run: ssh -oStrictHostKeyChecking=no serveurdev@test.pepintrie.fr ./launch.sh

