name: deploy-serv-dev

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install-java
        run: sudo apt update && sudo apt -y install default-jdk
      - name: build plugin
        run: jar cf plugin.jar .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          username: serverdev
          debug: true
          port: 22
          script: 
            ./launch.sh

