name: deploy-serv-dev

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: linter
        run: echo "todo"
  deploy:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        uses: vazco/github-actions-branch-name@v1
        id: branch
      - name: Echo branch name
        run: echo "${{ steps.branch.outputs.branch_name }}"

      - name: SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
          username: serverdev
          host: test.pepintrie.fr
          command : ./launch.sh ${{ steps.branch.outputs.branch_name }}

