name: deploy-serv-dev

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install-java
        run: sudo apt update && sudo apt -y install default-jdk
      - name: build plugin
        run: jar cf plugin.jar .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
          username: serverdev
          host: test.pepintrie.fr
          command : ./launch.sh ${GITHUB_REF#refs/heads/}

